RESOLUTION = WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
FPS = 60
DELAY_TIME = 700

HOME_FONT_SIZE = 100
HOME_SCORE_FONT_SIZE = 450
HOME_SCORE_POS = 200, 90
HOME_MARGIN = 50
HOME_PADDING = 20
HOME_START_X = HOME_MARGIN
HOME_START_Y = 250
HOME_START_WIDTH = WINDOW_WIDTH - HOME_MARGIN*2
HOME_START_HEIGHT = HOME_FONT_SIZE + HOME_PADDING
HOME_EXIT_X = HOME_MARGIN
HOME_EXIT_Y = HOME_START_Y + HOME_START_HEIGHT + HOME_MARGIN
HOME_EXIT_WIDTH = HOME_START_WIDTH
HOME_EXIT_HEIGHT = HOME_START_HEIGHT


ROWS, COLS = 2, 2
BTN_WIDTH = WINDOW_WIDTH / COLS
BTN_HEIGHT = WINDOW_HEIGHT / ROWS
BTN_NAME_TAG_OFFSET_X = BTN_NAME_TAG_OFFSET_Y = 30
BTN_TAG_FONT_SIZE = 200
BTN_TAG_COLOR = (255, 255, 255)
BTN_TAG_COLOR_ALPHA = 120
BTN_DEACTIVATE_TIME = 400

BLUE = 'blue'
RED = 'red'
GREEN = 'green'
ORANGE = 'orange'
BLACK = 'black'
WHITE = 'white'
