RESOLUTION = WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
FPS = 10
DELAY_TIME = 700

ROWS, COLS = 2, 2
BTN_WIDTH = WINDOW_WIDTH / COLS
BTN_HEIGHT = WINDOW_HEIGHT / ROWS
BTN_NAME_TAG_OFFSET_X = BTN_NAME_TAG_OFFSET_Y = 40
BTN_TAG_FONT_SIZE = 100
BTN_TAG_COLOR = (170, 170, 170)

BLUE = 'blue'
RED = 'red'
GREEN = 'green'
ORANGE = 'orange'
