RESOLUTION = WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
FPS = 10
DELAY_TIME = 700

ROWS, COLS = 2, 2
BTN_WIDTH = WINDOW_WIDTH / COLS
BTN_HEIGHT = WINDOW_HEIGHT / ROWS
BTN_NAME_TAG_OFFSET_X = BTN_NAME_TAG_OFFSET_Y = 30
BTN_TAG_FONT_SIZE = 200
BTN_TAG_COLOR = (255, 255, 255)
BTN_TAG_COLOR_ALPHA = 100

BLUE = 'blue'
RED = 'red'
GREEN = 'green'
ORANGE = 'orange'
